刘欣钰 task01
IRobot-EC-2024/welcome pull request #104
Opened 2024-09-21 16:52 UTC by bbbbbbb1215

2024-09-22 07:54 UTC, H0pefu12 commented
请使用“文件->导出”功能将原理图和PCB导出为PDF或图片

2024-09-23 19:34 UTC, lunarifish requested changes
看起来用的是默认10mil线宽，10mil=0.254mm，想一想这么细的线会不会导致什么问题

2024-09-28 14:42 UTC, WestNorth-Wolf requested changes
请再思考一下线宽与通过电流之间的关系并选择合适线宽，请参考开源方案的PCB板。

2024-09-29 09:07 UTC, WestNorth-Wolf commented
请检查你的铺铜区域为何是不规则的，且你的PCB设计存在drc错误

2024-09-30 00:14 UTC, merged