task1
IRobot-EC-2024/welcome pull request #111
Opened 2024-09-22 08:56 UTC by XDai-Dai

2024-09-22 11:06 UTC, H0pefu12 commented
不要再项目中添加其他任务无关文件！

2024-09-28 14:44 UTC, WestNorth-Wolf requested changes
线宽不对，请思考线宽与通过电流的对应关系，参考开源方案，缺少输出端口（参考输入端口设计）。

2024-09-29 05:43 UTC, WestNorth-Wolf requested changes
请进行drc检查，检查无误后再提交。

2024-09-29 08:12 UTC, WestNorth-Wolf commented
仍有drc错误？那个x代表你drc过了吗？

2024-09-29 11:18 UTC, merged