更改任务一
IRobot-EC-2024/welcome pull request #123
Opened 2024-09-23 08:56 UTC by chenmixuexi5983

板子太小了，没法焊，改一下。
顺便修一下任务零的小bug。

2024-09-23 19:28 UTC, lunarifish requested changes
1. 实际应用的的板子和元件就是这么小，能焊这样的板子是能胜任工作的条件之一

2. 思考一下这么细的线会不会导致什么问题

2024-09-23 23:27 UTC, chenmixuexi5983 commented
把线改粗了一点

2024-09-27 14:30 UTC, chenmixuexi5983 commented
有人么？

2024-09-29 02:38 UTC, WestNorth-Wolf commented
请更改一下铺铜规则，铺铜区与焊盘连接线宽不够

2024-09-29 15:52 UTC, chenmixuexi5983 commented
改了，顺便提交一下焊好的板子，功能不算太好，如果需要的话，我过两天把改好的板子下单再焊一次。

2024-09-30 04:40 UTC, merged