task1 resubmit
IRobot-EC-2024/welcome pull request #160
Opened 2024-09-29 14:26 UTC by ShenlongEZAM

加入了原理图与输入输出端口

2024-09-30 02:01 UTC, Specific-Cola requested changes
学习一下铺铜，注意线宽，

2024-09-30 09:59 UTC, ShenlongEZAM commented
![87f1afaf-c817-4eb8-b33a-bf5ff9c144bb](https://github.com/user-attachments/assets/0537bf38-3d81-44b1-8472-f3d9bd39a41c)
![d0489c68-ba4c-452b-93ec-bd5d4dd156f5](https://github.com/user-attachments/assets/6767a599-4b60-465b-9f27-395bea0f7392)
改了线路铺了铜并且在大电流处加粗线宽

2024-10-01 02:19 UTC, WestNorth-Wolf commented
还有地方线宽注意一下，发散连接处

2024-10-02 02:40 UTC, ShenlongEZAM commented
修改了电源线宽地线全采用发散链接

2024-10-07 03:37 UTC, WestNorth-Wolf commented
把发散的改成直连，是我没表达清楚，sorry

2024-10-08 11:25 UTC, WestNorth-Wolf commented
改直连，端口建议不要在板中间

2024-10-08 11:46 UTC, ShenlongEZAM commented
改了端口位置

2024-10-08 11:49 UTC, WestNorth-Wolf commented
板边缘的过孔好像没什么用？不要把过孔打在焊盘上（降压芯片的一个焊盘）。补充上传PCB底层布线图

2024-10-09 06:11 UTC, ShenlongEZAM commented
1.网上教程说过孔增加顶层底层连接[](url)
![75658478-5770-4982-95c3-f4e9cf66e614](https://github.com/user-attachments/assets/8362049d-1837-48c0-9933-8c3b938f0c7a)
2.以下移改过孔位置
3.已补充
4.已在不扩大板面积情况下增大部分器件距离

2024-10-09 08:12 UTC, WestNorth-Wolf commented
1. 你学习了铺铜发散和直连的区别，很好，但是建议电源网络直连，增大散热，避免工作时发热。
2. 过孔要打在铺铜的地方才能增加过电流连接性，你现在只是打了几个机械孔罢了。

2024-10-09 08:13 UTC, merged