任务1
IRobot-EC-2024/welcome pull request #161
Opened 2024-09-29 15:19 UTC by silish11111

2024-09-30 01:59 UTC, Specific-Cola requested changes
加一个输入输出端口

2024-09-30 13:59 UTC, silish11111 commented
已更改

2024-10-01 02:17 UTC, WestNorth-Wolf commented
更改的是不对的，请理解什么叫输入输出，以及其电气意义

2024-10-07 03:29 UTC, WestNorth-Wolf commented
输入输出要有正负极，电路是回路，注意线宽与铺铜直连。

2024-10-10 13:17 UTC, merged

2024-10-10 13:18 UTC, WestNorth-Wolf commented
当心网络间距，小心短路。